### PR TITLE
update requirement changes from upstream

### LINKED ISSUE #42: incorrect version requirement for asteval
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

as of [version 1.1.0](https://github.com/lmfit/lmfit-py/releases/tag/1.1.0) `asteval > 0.9.28` is specified, but that was not updated here it seems.

### Installed packages

```shell
asteval:                 0.9.23-pyhd8ed1ab_0        conda-forge
    lmfit:                   1.2.2-pyhd8ed1ab_0         conda-forge
```

### Environment info

```shell
active environment : build
    active env location : C:\ProgramData\Miniconda3\envs\build
            shell level : 1
       user config file : C:\Users\user\.condarc
 populated config files : C:\ProgramData\Miniconda3\envs\build\.condarc
          conda version : 23.7.2
    conda-build version : 3.26.0
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __win=0=0
       base environment : C:\ProgramData\Miniconda3  (writable)
      conda av data dir : C:\ProgramData\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : c:\programdata\miniconda3\pkgs
       envs directories : C:\ProgramData\Miniconda3\envs
               platform : win-64
             user-agent : conda/23.7.2 requests/2.31.0 CPython/3.11.4 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by theavey**
they've been out of date for a bit

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #42 

Not sure if there is a way to retract/remove the current 1.2.2 with the incorrect version requirements, but that seems advisable, otherwise the "bad" version may be preferred on installs because of the looser requirements.

### CODE REVIEW

**Comment by theavey** [comment]
@conda-forge-admin, please rerender

**Comment by tacaswell** [comment]
May be better to just patch the metadata via: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock

If we merge this thet well will have to yank the existing artifacts as the solver will still happily install it (it is easier to install!).

**Comment by theavey** [comment]
I didn't know/don't know about that, but agree that the old build existing would be an issue (would get installed).

**Comment by tacaswell** [comment]
I suggest following https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/465/files (but get the time units right!)

**Comment by newville** [comment]
@theavey @tacaswell thanks.  Not being very conversant in the conda-forge world, I'm afraid I don't quite understand how to use https://github.com/conda-forge/conda-forge-repodata-patches-feedstock.  Is the idea that it updates the recipe based on the project's `setup.cfg` file?

**Comment by tacaswell** [comment]
Conda works from a json blob of the metadata (rather than what is in the files )which we can not change so we do not invalidate any hashes)).

That repo lets you edit the metadata that is served from the cf channel to be correct so the solver has correct information.

The format of the file is pretty straight forward, you specify what version you want to change and then you get access to a dict of the meta data to mutate how ever you want.  There is also some pretty nice tooling around it.

**Comment by newville** [comment]
@tacaswell It may very well be that I don't understand, but I would definitely favor fixing the recipe (source code) than manipulating the result. 

Again, maybe I am not understanding your point.  I really do not do much with conda recipes anymore.  Then again, any recipe for any packaging system (conda, MacPorts, Debian) for a pure Python package like lmfit that is something other than `python -m pip install lmfit` has the potential to fall out of sync with the correct installation method.

**Comment by tacaswell** [comment]
You (@newville) need to do both: fix the metadata for the already published packages and fix the recipe going forward.  I don't have a point other than trying to help you out.

----

The pip/wheel packaging ecosystem is just one of many valid packaging ecosystems and has many issues (see https://pypackaging-native.github.io).

**Comment by newville** [comment]
@theavey thanks - I'll merge this to fix the recipe.  

I do not understand the suggestion from @tacaswell or have a clue how to "follow" that other example. Like, I do not see what actions would be taken to do that, or even what "that" is or why that would be desirable.   I just have no idea what that example is about or why that is relevant.  Not arguing that it shouldn't be done, just no idea what it is.

If someone else understands that and thinks it is relevant here, feel free to do that.

**Comment by tacaswell** [comment]
@newville See the direction at https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/main/recipe .

Ping me when you open a PR and I can help make sure it gets through review over there.

**Pull request merged**
