### PR TITLE
Fixed sha sum.

### LINKED ISSUE #30: lmfit 1.0.1?
Conda-forge [lists](https://anaconda.org/conda-forge/lmfit/) only lmfit 1.0.0. As far as I understand, the build of lmfit 1.0.1 [failed](https://github.com/conda-forge/lmfit-feedstock/commit/0cda2ee6e7c0fd5fb525ea6111226d6df8efe93a).

Can something be done?

### PR DESCRIPTION
**Pull request by angelo-peronio**
Should fix #30 . I hope I am doing this right.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by newville** [comment]
@angelo-peronio looks good to me.

**Comment by newville** [comment]
@angelo-peronio should we just merge this?

**Comment by angelo-peronio** [comment]
@newville Yes, please.

**Comment by newville** [comment]
@angelo-peronio OK, merging - thanks!

**Pull request merged**
