### PR TITLE
update recipe for 0.9.9

### PR DESCRIPTION
**Pull request by newville**
updates recipe to build lmfit 0.9.9
adds a dependency of asteval.

### CODE REVIEW

**Comment by jakirkham** [comment]
Please use a PR from a fork in the future. Pushing to branches on the main (non-forked) feedstock cause package deployment. This is an intentional featured used by other feedstocks like `python` and `numpy` to manage multiple versions.

**Comment by jakirkham** [comment]
Also please do not use the `master` version of `conda-smithy`. As noted elsewhere ( https://github.com/conda-forge/asteval-feedstock/pull/6 ) this is under development and not stable. Would encourage you to use `conda-smithy` version 2.4.5, which is the latest stable/released version of `conda-smithy`.

**Comment by newville** [comment]
@jakirkham Why is using a branch on a fork different is preferred over a non-master branch on origin?  Isn't  "causes package deployment" more or less the goal?  Seems like a feature to encourage to me.

I did install conda smithy 2.4.5.  Doing `conda smithy rerender` from a Py27 environment failed with

```
  File "/anaconda/bin/conda-smithy", line 11, in <module>
    load_entry_point('conda-smithy==2.4.5', 'console_scripts', 'conda-smithy')()
  File "/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/anaconda/lib/python2.7/site-packages/conda_smithy-2.4.5-py2.7.egg/conda_smithy/cli.py", line 14, in <module>
    from . import configure_feedstock
  File "/anaconda/lib/python2.7/site-packages/conda_smithy-2.4.5-py2.7.egg/conda_smithy/configure_feedstock.py", line 13, in <module>
    import conda.config
```

That doesn't really look like a conflict left over from installing master branch of conda-smithy to me, but maybe it is related.   

Not sure, so I deleted the broken appveyor config by hand.    And, yet again, there is *another* problem with the conda-forge generated script for one of the two Travis checks.   Not a problem with the package (lmfit-py) or the service (travis), only with the recipes generated by conda-forge. 

Hmm...

**Comment by jakirkham** [comment]
> Why is using a branch on a fork different is preferred over a non-master branch on origin? Isn't "causes package deployment" more or less the goal? Seems like a feature to encourage to me.

The benefit to a PR from a fork would be having the CIs validate everything. Then merging would actually perform the deployment.

For example, in this PR CircleCI already deployed, but Travis CI failed. Having not looked into the issue at all yet. If fixing Travis CI also resulted in changes for CircleCI, a build number bump would also be needed to get new packages for both platforms. While certainly doable this ends up being a bit more work than using a fork from the beginning and only deploying as part of the merge step once everything has checked out.

Another benefit is from the review perspective. For instance, suppose we found something we need to address in the recipes of this PR. Other maintainers have the option to discuss these concerns and come to some resolution before making the package public.

> I did install conda smithy 2.4.5. Doing `conda smithy rerender` from a Py27 environment failed with...

As `conda-smithy` is dependent on other `conda*` tooling (e.g. `conda`, `conda-build`, and `conda-build-all`), it needs to be installed in the `root` environment. Can understand if this is a bit of hassle. Some users opt to have a totally different `conda` install for `conda-smithy` because of this. The webservice is also a good solution to this problem as it requires no installation whatsoever.

**Comment by newville** [comment]
@jakirkham  Reviews can happen on branches or forks.  Your argument for fork v branch is not very persuasive...  I can certainly believe it is easier for conda-forge, but that's not very persuasive for me.

>>    I did install conda smithy 2.4.5. Doing conda smithy rerender from a Py27 environment failed with...

> As conda-smithy is dependent on other conda* tooling (e.g. conda, conda-build, and conda-build-all), it needs to be installed in the root environment. Can understand if this is a bit of hassle. Some users opt to have a totally different conda install for conda-smithy because of this. The webservice is also a good solution to this problem as it requires no installation whatsoever.

Uh well, yeah conda, conda-build, and conda-build-all *are* installed, and on a root environment.  `conda smithy rerender` fails with the message I gave above.

I have no idea what webservice you are talking about.  No mention of it was made before.  I don't really care to add one of these feedstocks polluting upstream repos.   I maintain conda recipes that work for other channels, and they take much less effort.

I  added  the `noarch` option to skip over the broken conda-forge tests.

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender

> I have no idea what webservice you are talking about.

ref: https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender

**Comment by jakirkham** [comment]
> Reviews can happen on branches or forks. Your argument for fork v branch is not very persuasive... I can certainly believe it is easier for conda-forge, but that's not very persuasive for me.

Sure they can. Just noting the pros/cons of doing so in different configurations. Also noting the additional ramifications within conda-forge. Using a fork is generally in keeping with what other OSS projects do. I'm sure there are exceptions though.

**Comment by jakirkham** [comment]
As to the `conda-smithy` problem, would encourage you to raise it at the [`conda-smithy` repo]( https://github.com/conda-forge/conda-smithy ) where someone can take a closer look.

**Comment by jakirkham** [comment]
Also cleared out the files from dev copy of `conda-smithy` in the last commit. Hope that is ok.

**Comment by CJ-Wright** [comment]
@newville please read the docs linked in the asteval PR you submitted and the discussion which happened there.
@conda-forge/lmfit this seems to be ready for review/merge.

**Comment by newville** [comment]
@CJ-Wright Um, I did read the conversation in the asteval PR... not sure what your point is.   

Sorry y'all, but I'm not really on the conda-forge bandwagon, so much of what I see from you all looks like "inside the mindset of conda-forge"...  I don't really care, and everything you suggest just looks like extra work to get around problems with conda-forge that maybe you're too involved with to see.    The advice given was most certainly to turn off and/or remove the CI scripts built by conda smithy and conda-forge because they do not work.  Again, the packages are fine, the conda recipes are fine, and all the CI services are working.  The package management scripts are not fine.  

If conda-forge is going to have `lmfit` and `asteval`, the recipe should be kept up to date.  I don't really care how that happens.   But if conda-forge cannot have working package management scripts, why should anyone bother to use it?

**Pull request closed without merging**
